name: Run Pause 

on:
  push:
  schedule:
   # 定时任务，北京时间2点执行任务 2:00（北京时间）-8:00 = -17:00(24进制)cron指定的是格林尼治时间（UTC），如果需要换算成北京时间，要在该cron的基础上增加八小时得到北京时间
    - cron: '00 21 * * *' #第一个数字代表分钟，第二个数字代表小时，第三个数字代表日，第四个数字代表月，第五个数字代表星期。

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Pause
        env:
          LEISHEN_USERNAME: ${{ secrets.LEISHEN_USERNAME }}
          LEISHEN_PASSWORD: ${{ secrets.LEISHEN_PASSWORD }}
        run: |
          python ./legod.py
